
#tools install defaults

prefix ?= ${DESTDIR}/usr/local
exec_prefix := $(prefix)
bindir := $(exec_prefix)/bin
data_dir := $(prefix)/share/emu10k1
man_prefix := $(exec_prefix)/man
script_dir := $(prefix)/etc
